/**
 * offline VSIX 的 ignore 规则由 .vscodeignore 生成(harness PR3 §8.2 v2)—— 纯逻辑,无 IO。
 *
 * 仓库里只有一份 ignore(.vscodeignore);offline 版 = 删掉标记注释 `# @offline-include`
 * 及其下方紧邻的 `offline-model/**`。两份文件手工同步的漂移在结构上不可能发生。
 * fail-closed:标记缺失 / 重复 / 下方不是 offline-model/** / 其他行也提到 offline-model → 抛错。
 *
 * "有效规则" 与 vsce 的解析一致(vsce collectFiles:按行 trim、去空行、去 # 注释)。
 */

export const OFFLINE_MARKER = '# @offline-include';
export const OFFLINE_RULE = 'offline-model/**';

const GENERATED_HEADER = [
  '# GENERATED by scripts/package-offline.mjs from .vscodeignore —— 不要手改,也不要提交。',
  `# 与 .vscodeignore 的唯一差异:去掉 ${OFFLINE_RULE}(内置模型随包)。`,
];

/** vsce 实际生效的规则(顺序保留;negation 规则顺序敏感)。 */
export function effectiveRules(text) {
  return text
    .split(/[\n\r]/)
    .map((s) => s.trim())
    .filter((s) => s && !s.startsWith('#'));
}

/**
 * @param {string} text .vscodeignore 全文
 * @returns {string} offline ignore 全文
 */
export function generateOfflineIgnore(text) {
  const lines = text.split(/\r?\n/);
  const markers = lines.flatMap((l, i) => (l.trim() === OFFLINE_MARKER ? [i] : []));
  if (markers.length === 0) throw new Error(`.vscodeignore 缺少标记 "${OFFLINE_MARKER}"(应放在 ${OFFLINE_RULE} 上一行)`);
  if (markers.length > 1) throw new Error(`.vscodeignore 标记 "${OFFLINE_MARKER}" 出现 ${markers.length} 次(只允许 1 次)`);
  const at = markers[0];
  if (lines[at + 1]?.trim() !== OFFLINE_RULE) {
    throw new Error(`.vscodeignore 标记 "${OFFLINE_MARKER}" 下一行必须是 ${OFFLINE_RULE},实际: ${JSON.stringify(lines[at + 1] ?? '(文件结束)')}`);
  }
  const out = lines.filter((_, i) => i !== at && i !== at + 1);
  const stray = effectiveRules(out.join('\n')).filter((r) => r.includes('offline-model'));
  if (stray.length > 0) {
    throw new Error(`.vscodeignore 在标记之外还有涉及 offline-model 的规则(会让两种包的差异不止一行): ${stray.join(', ')}`);
  }
  return [...GENERATED_HEADER, ...out].join('\n');
}

/**
 * standard → offline 的有效规则差异(按规则计数,顺序无关)。PR 级 dry-run 断言它恰为
 * { removed: [offline-model/**], added: [] }。
 */
export function ruleDiff(standardText, offlineText) {
  const count = (rules) => rules.reduce((m, r) => m.set(r, (m.get(r) ?? 0) + 1), new Map());
  const a = count(effectiveRules(standardText));
  const b = count(effectiveRules(offlineText));
  const removed = [];
  const added = [];
  for (const [r, n] of a) for (let k = n - (b.get(r) ?? 0); k > 0; k--) removed.push(r);
  for (const [r, n] of b) for (let k = n - (a.get(r) ?? 0); k > 0; k--) added.push(r);
  return { removed, added };
}

/** 差异不是"恰好少一条 offline-model/**" → 返回违规描述。 */
export function checkRuleDiff({ removed, added }) {
  const errors = [];
  if (added.length > 0) errors.push(`offline ignore 多出规则: ${added.join(', ')}`);
  if (removed.length !== 1 || removed[0] !== OFFLINE_RULE) {
    errors.push(`offline ignore 与 .vscodeignore 的差异应恰为去掉 ${OFFLINE_RULE},实际去掉: ${removed.join(', ') || '(无)'}`);
  }
  return errors;
}
